### ISSUE TITLE
Usecase for forcing default in config_collection_for_built?

### ISSUE THREAD

**Issue by lathonez** [ianmiell/shutit#144]
Unpicking configs again, sorry.

```python
def config_collection_for_built(shutit):
        """Collect configuration for modules that are being built.
        When this is called we should know what's being built (ie after
        dependency resolution).
        """
        for module_id in module_ids(shutit):
                # Get the config even if installed or building (may be needed in other
                # hooks, eg test).
                if (is_to_be_built_or_is_installed(shutit, shutit.shutit_map[module_id]) and
                        not shutit.shutit_map[module_id].get_config(shutit)):
                                shutit.fail(module_id + ' failed on get_config')
                # Collect the build.cfg if we are building here.
                # If this file exists, process it.
                if shutit.cfg[module_id]['shutit.core.module.build']:
                        module = shutit.shutit_map[module_id]
                        cfg_file = os.path.dirname(module.__module_file) + '/configs/build.cnf'
                        if os.path.isfile(cfg_file):
                                # use shutit.get_config, forcing the passed-in default
                                config_parser = ConfigParser.ConfigParser()
                                config_parser.read(cfg_file)
                                for section in config_parser.sections():
                                        if section == module_id:
                                                for option in config_parser.options(section):
                                                        override = False
                                                        for mod, opt, val in shutit.cfg['build']['config_overrides']:
                                                                # skip overrides
                                                                if mod == module_id and opt == option:
                                                                        override = True
                                                        if override:
                                                                continue
                                                        is_bool = (type(shutit.cfg[module_id][option]) == bool)
                                                        if is_bool:
                                                                value = config_parser.getboolean(section,option)
                                                        else:
                                                                value = config_parser.get(section,option)
                                                        if option == 'shutit.core.module.allowed_images':
                                                                value = json.loads(value)
                                                        shutit.get_config(module_id, option,
                                                                          value, forcedefault=True)
```

Basic question is, why are we passing forcedefault=True on the last line here? This was obviously put in deliberately. I need to understand why so I can figure out if I'm using shutit config wrong.

This is along the same lines as [PR 133](https://github.com/ianmiell/shutit/pull/133). In that PR I found that my command line args were getting overwritten by build.cnf of any module I was building (shutit.core.module.build:yes).

In this instance, I want to override configs in dependee modules using build.cnf in the module I'm running build.sh from (e.g. the local configs/build.cnf), as opposed to using the command line. This works if I remove forcedefault=True above.

Example - module b depends on module a:

com/corp/module_a/configs/build.cnf:

```
[com.corp.module_a.module_a]
example_config:SETME
```

com/corp/module_b/configs/build.cnf:

```
[com.corp.module_a.module_a]
shutit.core.module.build:yes
example_config:OVERRIDING_SETME
```

I then run

```
com/corp/module_b/bin/build.sh.
```

This loads my OVERRIDING_SETME fine from com/corp/module_b/configs/build.cnf (initially), but then it overrides it with SETME, in config_collection_for_built (code snippet above).

I'd propose just removing the forcedefault=true, but I don't know what it's there for.

**Comment by aidanhs** [comment]
Wouldn't loading the build.cnfs in run order fix this?

**Comment by ianmiell** [comment]
Are they not already? oops.

**Comment by aidanhs** [comment]
Oh no, they should be (`module_ids` call). Odd. I don't understand how module A overrides module B in @lathonez's example.

**Comment by lathonez** [comment]
It's because the local configs/build.cnf is loaded before everything else. Let me find the code.

**Comment by lathonez** [comment]
Hmm, I think I just have an odd usecase. In my example module_b isn't configured to be built. If it was, it would be overwritten according to @aidanhs 

So, if this isn't valid we can close it.. Trying to think of a more useful example.

**Comment by aidanhs** [comment]
Building all deps seems like a reasonable thing to want to do, though I don't quite see how you're getting as far as you are at the moment - if you have a module A depending on B, C and D, what magic do you perform to build B, C and D?
My approach would probably be to add another command line switch, `--build_deps_of <moduleid>` but clearly you have a current working method?

**Comment by lathonez** [comment]
I wouldn't go that far. I pass them in on the command line via build.sh of module a. `-s module_b shutit.core.module.build yes -s module_c shutit.core.module.build yes -s module_d shutit.core.module.build yes`, but depending on the switches passed into build.sh module_a won't actually be built.

**Comment by aidanhs** [comment]
I see, it's effectively manual then.
Not quite clear how the build.cnf of module a gets involved then. Via `--config`? I probably just need a concrete code example - you can point me at one tomorrow hopefully.

**Comment by lathonez** [comment]
As discussed, this is quite a lot more complicated than it initially seems.

At it's most basic, this is just about being able to pass a config file through --config, and having the sections in that config file overwrite everything else in the config stack (aside from other command line arguments).

Trying to do a simple example - this should work with any module, I've used win2048

-1. Add a test config to configs/build.cnf:

```
# When this module is the one being built, which modules should be built along with it by default?
# This feeds into automated testing of each module.
[shutit.tk.win2048.win2048]
shutit.core.module.build:yes
# Allowed images, eg ["ubuntu:12.04"].
# "any" is a special value meaning any image is ok, and is the default.
# It's recommended this is locked down as far as possible.
shutit.core.module.allowed_images:["ubuntu.*"]
test_config:SETME
```

-2. Create a new config file (test.cnf) overriding the above:

```
[shutit.tk.win2048.win2048]
test_config:OVERRIDE
```

-3. Run shutit in show config mode - the test_config value is not overwritten:

```
scutty:~/shutit/library/win2048$ shutit --sc --config configs/test.cnf 

Looking at config files in the following order:

    
defaults    
/home/shazleto/shutit/configs/scutulum_shazleto.cnf    
/home/shazleto/.shutit/config    
configs/build.cnf    
configs/test.cnf

[Hit return to continue]
...
[shutit.tk.win2048.win2048]
shutit.core.module.allowed_images:[u'ubuntu.*']
shutit.core.module.build:True
shutit.core.module.build_ifneeded:False
shutit.core.module.remove:False
shutit.core.module.tag:False
test_config:SETME
```

Briefly, the problem is that although we load all of the "base config" files into `shutit.cfg['config_parser']`, we don't explicitly load the sections into the shutit.cfg['module_id']['option'] array. By "base config" files I mean the following:

* ~/.shutit/config
* shutit/configs/hostname_username.cnf
* local configs/build.cnf
* any config file passed in with --config

This is different to the way we load all the build.cnf files in (config_collection and config_collection_for_built). In these we have logic which iterates over the options found in the config:

```python
	for option in config_parser.options(section):
		...
		shutit.get_config(module_id, option,
		                  value, forcedefault=True)
```

I'll leave this with you for now. Let me know if you need more info or want me to do something.

For now I can solve my issue by using command line args, as they will always overwrite.

**Comment by ianmiell** [comment]
Thanks - nice, clear example. I'll have a think, but probably not before
next week.

**Comment by lathonez** [comment]
No rush, I've a workaround.

**Comment by ianmiell** [comment]
Closing off, Shazzer!
