### ISSUE TITLE
Bug in Docker?

### ISSUE THREAD

**Issue by ianmiell** [ianmiell/shutit#151]
On CentOS:

git clone https://github.com/ianmiell/shutit-coreos-do.git
cp dockerfile/Dockerfile.eg dockerfile/Dockerfile
cd dockerfile
docker build --no-cache .

hangs. Doesn't seem to happen on Ubuntu.

Tried latest version of docker, same thing. pexpect versions same.

**Comment by ianmiell** [comment]
Only for docker build btw, shutit build is fine.

**Comment by ianmiell** [comment]
OK, I've worked around this by using cp when in delivery == bash, but the bug is still "there".

**Comment by aidanhs** [comment]
```
$ git clone https://github.com/ianmiell/shutit-coreos-do.git
$ cd shutit-coreos-do/cluster_setup/dockerfile
$ docker run -i -t -v $(pwd):/xx -v /usr/bin/docker:/usr/bin/docker -v /var/run/docker.sock:/var/run/docker.sock -w /xx --rm centos:6.6 bash
# cp Dockerfile.eg Dockerfile.eg
# docker build --no-cache .
[...]
```

Tried to reproduce this in a docker centos container running docker, but no joy. What version of centos/when does it hang? Note I didn't change the access token so the shutit module doesn't do anything.

**Comment by ianmiell** [comment]
Ah, should have clarified - the bug occurred when sending a file to the container (python env) in bash delivery. I changed shutit to simply cp when doing bash delivery.

To repro, remove that if block in the code for bash delivery and rerun. Not sure it would repro in a docker container tho.

**Comment by ianmiell** [comment]
Can't repro now even with specific version checked out:

git clone https://github.com/ianmiell/shutit-coreos-do.git
cd shutit-coreos-do/cluster_setup
cp dockerfile/Dockerfile.eg dockerfile/Dockerfile
cd dockerfile
sed -i 's/sd_shutit/sd_shutit:bug151/' Dockerfile
docker build --no-cache .
