### ISSUE TITLE
./run.sh: hardcoded docker executable

### ISSUE THREAD

**Issue by mromaniOB** [ianmiell/shutit#157]
Step 5 in http://ianmiell.github.io/shutit/ fails if the environment needs a different docker executable, e.g. `sudo docker` instead of just `docker`.

**Comment by mromaniOB** [comment]
It was mentioned in a 2014 comment that the env variable DOCKER should be set if one neede a different docker command.
Here's a modified run.sh that takes that into account:

```bash
#!/bin/bash
# Example for running

[ -z "$DOCKER" ] && DOCKER="docker"

docker_executable=$DOCKER

$docker_executable run -t -i my_module  /bin/bash
```

Example usage:
```bash
export DOCKER="sudo docker"
./run.sh
```

**Comment by mromaniOB** [comment]
Still, a mismatch could arise as the docker executable can be specified in `~/.shutit/config` like this (please correct me if I'm wrong):

```ini
[host]
docker_executable: sudo docker
```

**Comment by ianmiell** [comment]
Thanks!
Yes I'd prefer to use the config where necessary rather than more env vars.
I'll have a think (will probably make a note in the doc first).
I assume you're an openbetter? If you want to be added to the mailing list,
let me know your email addy.
Ian

**Comment by mromaniOB** [comment]
Yup, I am.
My e-mail is marcello.romani@openbet.com

As for the modified `run.sh` script, that was just a quick hack. I'd rather use config files too, but I figured it would take a bit more than a bash two-liner to get `docker_executable` value out of `~/.shutit/config` ;)
Still, I think that should be the preferred solution.
Do you have any hints as to what would be the preferred way to implement that?

**Comment by ianmiell** [comment]
You can pass configs in on the command line (in case you didn't know) to
shutit with -s, eg

-s host docker_executable "sudo docker.io"

but yes there could be a mismatch. The real purpose of run.sh is to provide
an example for running. Unfortunately there's various ways people run
docker (aliases, sudo, docker, docker.io) so covering them all is a pita.

I'm going to add a note to the io page for now.

Keep the feedback coming.

**Comment by ianmiell** [comment]
Have updated the doc with a few little tweaks, including your --user idea -
thanks!
Ian

**Comment by mromaniOB** [comment]
(To be fair, `pip`'s `--user` switch was suggested by a colleague of mine :-) )

**Comment by mromaniOB** [comment]
`-s` is in fact mentioned in `build -h` help text, though I haven't found a place where the config keys are listed. Maybe I haven't looked hard enough... Any pointers? Thanks!

**Comment by ianmiell** [comment]
I'd be happy to doc them, but the best pointer is here:

https://github.com/ianmiell/shutit/blob/master/util.py#L55

maybe I should link to that from the README....

**Comment by mromaniOB** [comment]
I think that would be useful...

**Comment by ianmiell** [comment]
Done.
Could still take the docker executable from the config when producing the run.sh script.
