### ISSUE TITLE
Container can't resolve archive.ubuntu.com, shutit job doesn't fail

### ISSUE THREAD

**Issue by mromaniOB** [ianmiell/shutit#158]
After creating a test module as per Step 2 and launching `./build.sh` as per Step 4, I noticed the `apt-get` commands failed due to DNS issues (the container doesn't have access to the DNS servers configured in its own `/etc/resolv.conf` file.)

Yet, the build job carried on and there was no clear indication of failure when it finished.

**Comment by ianmiell** [comment]
Hi,

That's an openbet thing :)

Aidan can explain it, but my internal OB wiki docs should go over this :)

The tl;dr is: add the dnses to your ~/.shutit/config as per the default
(doc'd in util.py):

# Information specific to the host on which the build runs.
[host]
# Docker executable on your host machine
docker_executable:docker
# space separated list of dns servers to use
*dns:*

Aidan/others will know the internal OB dns.

Ian

**Comment by mromaniOB** [comment]
Yup, I know it's an OpenBet thing. And I also have fixed that as you suggested. I was just pointing out that no error message appears at the end of the build in case the container has network access problems.

**Comment by ianmiell** [comment]
Yeah, that's apt's fault :) returns a 0 exit code in those cases. Never
been sure whether this was something to override or not.

[imiell@alberti /space/git/shutit]$ docker run -ti --dns 1.1.1.1 ubuntu
root@cfd77be55603:/# apt-get update
Err http://archive.ubuntu.com trusty InRelease

Err http://archive.ubuntu.com trusty-updates InRelease

Err http://archive.ubuntu.com trusty-security InRelease

Err http://archive.ubuntu.com trusty Release.gpg
  Could not resolve 'archive.ubuntu.com'
Err http://archive.ubuntu.com trusty-updates Release.gpg
  Could not resolve 'archive.ubuntu.com'
Err http://archive.ubuntu.com trusty-security Release.gpg
  Could not resolve 'archive.ubuntu.com'
Reading package lists... Done
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty/InRelease

W: Failed to fetch
http://archive.ubuntu.com/ubuntu/dists/trusty-updates/InRelease

W: Failed to fetch
http://archive.ubuntu.com/ubuntu/dists/trusty-security/InRelease

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty/Release.gpg
 Could not resolve 'archive.ubuntu.com'

W: Failed to fetch
http://archive.ubuntu.com/ubuntu/dists/trusty-updates/Release.gpg  Could
not resolve 'archive.ubuntu.com'

W: Failed to fetch
http://archive.ubuntu.com/ubuntu/dists/trusty-security/Release.gpg  Could
not resolve 'archive.ubuntu.com'

W: Some index files failed to download. They have been ignored, or old ones
used instead.
root@cfd77be55603:/# echo $?
0

**Comment by ianmiell** [comment]
Actually, could throw an error with multi-send - need a list of error messages...

**Comment by marcelloromani** [comment]
I was thinking something more hack-ish, such as doing a `ping -c 1 archive.ubuntu.com` and failing if does not return a success code.

**Comment by ianmiell** [comment]
Still no guarantee - I guess what I really need is a list of strings output when there's a problem so that I can catch them.

**Comment by mromaniOB** [comment]
I was thinking of adding a ping test or something like that (e.g. host
www.google.com) and fail the build if the exit code was not "success".

On 26 February 2015 at 12:37, Ian Miell <notifications@github.com> wrote:

> Still no guarantee - I guess what I really need is a list of strings
> output when there's a problem so that I can catch them.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ianmiell/shutit/issues/158#issuecomment-76171026>.
>



-- 
  <http://www.openbet.com> Marcello Romani  Developer   T: +44 208 742 1600




   E: marcello.romani@openbet.com  W: www.openbet.com    OpenBet Ltd
Chiswick Park Building 9
566 Chiswick High Rd
London
W4 5XT   <http://twitter.com/OpenBet_Ltd>
<http://www.linkedin.com/company/165331/>
<http://www.facebook.com/OpenBet>  *EGR
B2B Awards*
Five times winner of Sportsbetting Supplier of the Year 2010 - 2014
Winner of In-Play Betting Software of the Year 2014  This message is
confidential and intended only for the addressee. If you have received this
message in error, please immediately notify the postmaster@openbet.com and
delete it from your system as well as any copies. The content of e-mails as
well as traffic data may be monitored by OpenBet for employment and
security purposes. To protect the environment please do not print this
e-mail unless necessary. OpenBet Ltd. Registered Office: Chiswick Park
Building 9, 566 Chiswick High Road, London, W4 5XT, United Kingdom. A
company registered in England and Wales. Registered no. 3134634. VAT no.
GB927523612  [image: save paper]

**Comment by ianmiell** [comment]
Yes, but the command can still fail even if it's reachable, and return a 0
exit code.

**Comment by marcelloromani** [comment]
Oh, I see. Sorry for the repeated comment BTW :P
