### ISSUE TITLE
"Depends" value on skeleton creation is not written in .py file

### ISSUE THREAD

**Issue by mromaniOB** [ianmiell/shutit#159]
```bash
./shutit skeleton $HOME/shutit_modules/my_module my_module my.domain.com ssh_server ubuntu
```
```bash
grep depends $HOME/shutit_modules/my_module/my_module.py 
		depends=['shutit.tk.setup']
```

(I am reading the code to try and fix the issue.)

**Comment by ianmiell** [comment]
OK, I'll hold off fixing it myself for now :)
Ian

**Comment by mromaniOB** [comment]
I think there's some misquoting around line 1234 util.py, as that line is not executed.

**Comment by ianmiell** [comment]
The quoting is tortuous, but I think that's a red herring.

It simply wasn't implemented in the bare module used. I've done it now.

Ian

**Comment by mromaniOB** [comment]
Yup, shortly after I published that last comment I realised skel_depends was simply ignored if the `-d Dockerfile` option was not used (the bare template branch was executed, as you said.)
