### ISSUE TITLE
Modules in library/ vs. how to find a module's module_id

### ISSUE THREAD

**Issue by mromaniOB** [ianmiell/shutit#161]
Say I would like to add a ssh server to my docker container.

I have a look in library/ and see ssh_server

To have my module depend on that, I need its module id. As far as I understand there are two ways to find that out:

look at ssh_server/configs/build.cnf

look at ssh_server/ssh_server.py

Is there any other way? What is the recommended way (i.e. best practice) to obtain that information?

**Comment by ianmiell** [comment]
The .py is the place to look - that's where the dependency information is
taken from for the core. The config files are just text files.

Do you have any ideas for another way to manage this (maybe based on
previous experience of other CM)?

Ian

**Comment by mromaniOB** [comment]
I was thinking of adding a "list modules" command of sorts, which would also help the user see what modules are visible to shutit, possibly hinting to the need to add more -m directives.

Something along the lines of:

shutit --list-modules
<module_id>    <path>   <module description>

**Comment by ianmiell** [comment]
Yes, not a bad idea.

**Comment by ianmiell** [comment]
There's a list_modules, eg

shutit list_modules -m /path/to/modules

and

shutit list_modules -m /path/to/modules --long

which output tabular data

**Comment by ianmiell** [comment]
(just added, along with list_deps, and list_configs)
