### ISSUE TITLE
[proposal] library module ssh_server: allow ssh root login with configured password

### ISSUE THREAD

**Issue by mromaniOB** [ianmiell/shutit#164]
Rationale:
while trying to understand how to use the ssh_server module, I found you have to add
```init
[target]
password: 1234
```
to avoid having to provide a password when asked by the openssh install procedure (which you can't do if you're targeting a docker container).
I though that would set root password to `1234`, and allow me to login via ssh once I had run `/root/start_ssh_server` inside the container.
I kept getting login deined errors, until I realised I had to modify the sshd server configuration.

Not sure if this code should go straight into ssh_server.py or would be better placed in one's own module.

```diff
diff --git a/library/ssh_server/ssh_server.py b/library/ssh_server/ssh_server.py
index c8ecadb..d870588 100644
--- a/library/ssh_server/ssh_server.py
+++ b/library/ssh_server/ssh_server.py
@@ -36,6 +36,18 @@ class ssh_server(ShutItModule):
                        shutit.add_line_to_file('ps -ef | grep -w sshd | awk \'{print $2}\' | xargs kill', '/root/stop_ssh_server.sh')
                shutit.send('chmod +x /root/start_ssh_server.sh')
                shutit.send('chmod +x /root/stop_ssh_server.sh')
+
+               # To allow root ssh logins with the configured password,
+               # we need to amend /etc/ssh/sshd_config
+               # Line
+               # PermitRootLogin without-password
+               # has to become
+               # PermitRootLogin yes
+               if not shutit.remove_line_from_file('PermitRootLogin without-password', '/etc/ssh/sshd_config'):
+                       return False
+               if not shutit.add_line_to_file('PermitRootLogin yes', '/etc/ssh/sshd_config'):
+                       return False
+
                return True
 
        def start(self, shutit):
```

**Comment by ianmiell** [comment]
If you want credit, you need to raise a PR :) If you don't mind, I'll merge in - let me know.

In the meantime I've tidied up the config acquisition somewhat.

**Comment by ianmiell** [comment]
Oh, and I've changed it to make it a config of the ssh server. Not sure whether that's a good idea or not now.

**Comment by mromaniOB** [comment]
Credit: merge it, n.p. :)

On second thought, maybe the module is not supposed to allow remote root logins and the password bit is just to avoid the interactive password request?

**Comment by ianmiell** [comment]
Actually, I should probably remove this module completely now that docker exec exists. I'll have a think, but that may be the path I take.

**Comment by mromaniOB** [comment]
Dunno. Though not strictly required to get a shell on a container, as a building block I think "install and configure an ssh server"-module could still be useful.

**Comment by mromaniOB** [comment]
FWIW, I think changing [target] to [ssh module id] in config makes sense.

**Comment by mromaniOB** [comment]
Speaking of 5d7ad430434fe62c9c082bebc327e90e13d9f0ad, I noticed you added a "hint" for the config parameter. Is there a way to programmatically display those?

**Comment by ianmiell** [comment]
You mean like a "list all possible configs" command?

**Comment by mromaniOB** [comment]
(Just noticed the "hint" is displayed if build is called with --interactive 1)

As a companion to "module list" (#161) it would be probably nice to have some sort of `module config <module_name>`, which ideally should list all module's config parameters, along with their hints.

Maybe you were thinking the same?

**Comment by ianmiell** [comment]
Yeah - much more motivated to work on it when others request it though :)

There was a bug with the hint which meant it wasn't displayed until today.

interactive 1+ should be the default - was this not the case for you?

Ian

**Comment by mromaniOB** [comment]
Just checked, the default is --interactive 1, therefore if the password is not provided, the user is asked for it just once, then the build proceeds successfully.

**Comment by ianmiell** [comment]
Assuming OK to close.

**Comment by mromaniOB** [comment]
Yes.
