### ISSUE TITLE
quickstart doesn't work

### ISSUE THREAD

**Issue by haf** [ianmiell/shutit#176]
```
vagrant@vagrant-ubuntu-trusty-64:~$ shutit skeleton $HOME/shutit_modules/my_module my_module my.domain.com --depends shutit.tk --image_tag ubuntu
usage: ShutIt [-h] [--version]
              {build,list_configs,list_modules,list_deps,serve,skeleton} ...
ShutIt: error: unrecognized arguments: --image_tag ubuntu
```

**Comment by ianmiell** [comment]
Thanks for raising this, and sorry it didn't work for you.
I'll check it in an hour or so (out now).

**Comment by ianmiell** [comment]
This is the correct call. I've updated and pushed the docs.

shutit skeleton $HOME/shutit_modules/my_module my_module my.domain.com
--depends shutit.tk --base_image ubuntu

Thanks again for raising!

Ian

**Comment by ianmiell** [comment]
Another correction, it's shutit.tk.setup it depends on:

shutit skeleton $HOME/shutit_modules/my_module my_module my.domain.com
 --depends shutit.tk.setup --base_image ubuntu

**Comment by haf** [comment]
Ok, thanks. It's also a bit confusing whether I should listen to the text in the executable which is a part of the tutorial, or if I should continue with the tutorial.

Anyway, I've made it all the way to successfully launching mysql.

What I find really hard about docker is to know how to tie everything together... I want stateless app containers, in an overlay network, with an ip-per-container, encrypted communication, auto-enlistment in service discovery as well as auto-routing of http and other application protocols to the actual services from the public endpoint...

Currently I'm looking at this combo:

 - **[coreos](https://coreos.com/)** with docker for the base distro
 - **[shutit](https://ianmiell.github.io/shutit/)** for creating images (most basic linux there is)
 - **[swarm](https://github.com/docker/swarm/)** for scheduling of spawning of containers (see [filters](https://github.com/docker/swarm/tree/master/scheduler/filter) for constraint scheduling. in future mesos backend is possible) and reconfiguring load balancers
 - **systemd** for starting apps inside containers
 - **[weave](https://github.com/zettio/weave#weave---the-docker-network)** for secure networking between containers and DNS
 - **[osquery](https://github.com/facebook/osquery/wiki/Deployment)** for ops inside containers
 - **[synapse](https://github.com/airbnb/synapse)** for service discovery

How would that work with shutit?

It's also scary to use your os build as opposed to something that has more uptake -- it might be worth mentioning something about that in your tutorial and to suggest how to move on from running the tutorial.

**Comment by ianmiell** [comment]
Hi Henrik,

Thanks for the feedback.


On Sat, Feb 21, 2015 at 11:48 AM, Henrik Feldt <notifications@github.com>
wrote:

> Ok, thanks. It's also a bit confusing whether I should listen to the text
> in the executable which is a part of the tutorial, or if I should continue
> with the tutorial.
>
Yes, I wonder whether I should get rid of the tutorial mode, as it's
probably too many avenues of documentation. I'll probably simply get rid of
it.

> Anyway, I've made it all the way to successfully launching mysql.
>
> What I find really hard about docker is to know how to tie everything
> together... I want stateless app containers, in an overlay network, with an
> ip-per-container, encrypted communication, auto-enlistment in service
> discovery as well as auto-routing of http and other application protocols
> to the actual services from the public endpoint...
>
> Currently I'm looking at this combo:
>
>    - *coreos <https://coreos.com/>* with docker for the base distro
>    - *shutit <https://ianmiell.github.io/shutit/>* for creating images
>    (most basic linux there is)
>    - *swarm <https://github.com/docker/swarm/>* for scheduling of
>    spawning of containers (see filters
>    <https://github.com/docker/swarm/tree/master/scheduler/filter> for
>    constraint scheduling. in future mesos backend is possible) and
>    reconfiguring load balancers
>    - *systemd* for starting apps inside containers
>    - *weave <https://github.com/zettio/weave#weave---the-docker-network>*
>    for secure networking between containers and DNS
>    - *osquery <https://github.com/facebook/osquery/wiki/Deployment>* for
>    ops inside containers
>    - *synapse <https://github.com/airbnb/synapse>* for service discovery
>
> How would that work with shutit?
>
That's a lot of technologies to get to grips with at once!

ShutIt is designed to plug different modular applications into a single
container (Dockerfiles are against this, or not designed for it), for when
you don't want to go the microservices route (there's an operational
overhead for microservices which may not be worth the effort for your use
case - shutit was built because we had a massive legacy system to
containerize quickly).

So in this case I'd probably have your app as a module and make it depend
on the osquery build and a systemd one (do you have an example for that?).
Weave may go in too, as well as synapse, but I don't know these
applications very well. If you have dockerfiles for whatever you want to
include, I can show you how to easily turn them into shutit modules.


> It's also scary to use your os build as opposed to something that has more
> uptake -- it might be worth mentioning something about that in your
> tutorial and to suggest how to move on from running the tutorial.
>
Good point, thanks! What do you mean by "os build" here, as I'm not sure?

**Comment by haf** [comment]
Yes, there are a few, but there are many technologies in a standard distro as well; having them explicit here doesn't make it much worse than the hidden complexity in distros, imo. As long as they can work together; but of this I'm not sure.

With OS build: I'm most familiar with CentOS, but I've gotten pretty tired of how hard it is to find proper packages for it. Since I'm writing F# and need a mono baseline, I have to build from source always - packages are too slow to update in official repos - that's why shutit was interesting. Plus, I like to have everything reproducible locally.

**Comment by ianmiell** [comment]
OK, I assume you've seen/heard of shutit-distro?

**Comment by haf** [comment]
Yes, that's what I was referring to when I said "os build" - how do I know it'll be in a working state? It seemed a lot of packages were built from trunk/master and then someone most likely needs to maintain the build scripts?

**Comment by ianmiell** [comment]
Ah ok!
Yes, validating whether the build is working is the reason for the "test"
part of the ShutIt lifecycle, which is run at the end.
The build scripts do need maintaining, hence there is CI on them here

https://registry.hub.docker.com/u/imiell/shutit-distro/builds_history/141321/

but the risk of drift is reduced due to using the linux from scratch
commands, which are well-maintained.

It would be my aim to avoid using trunk/master where possible - most of
these were put together in a hurry! Do you have any packages you want
attention on?

Ian

**Comment by ianmiell** [comment]
Had a look through the tutorial, and it looks up to date to me.
Made a couple of minor tweaks.
If things seem wrong/incomplete, let me know.
Ian

**Comment by haf** [comment]
Ok, great :). Thanks.

Having the mono package well taken care of, as well as the systemd one would be great. =)

**Comment by ianmiell** [comment]
OK :)
If you'd like to be added to the shutit mailing list, let me know your
email address.
Mine is ian.miell@gmail.com if you'd rather it was kept off github.
Ian

**Comment by ianmiell** [comment]
I see mono exists, but systemd doesn't, so I'll look at adding that.

Anything you'd like improved about the mono one, eg made smaller?

Ian

**Comment by haf** [comment]
Actually, I don't know at this point. I discovered ShutIt as a really nice concept just a day ago when researching the tooling that we're going to use, but I don't think we'll start working with these tools for another two weeks at least.

I can be very intensive to have as a user, so don't worry; there will be questions and suggestion coming this way ;).

The big question is 'does this compose with the rest of the tools? This is the latest iteration of the list of software:


 - **[coreos](https://coreos.com/)** with docker for the base distro
 - **[swarm](https://github.com/docker/swarm/)** for talking to the docker cluster as a single node and spawning of containers (see [filters](https://github.com/docker/swarm/tree/master/scheduler/filter) for constraint scheduling. Needs **[consul](https://consul.io)** as *discovery backend*.
 - **[consul](https://consul.io)** for service discovery, health monitoring (via its web UI). Runs on every container. Does [http checks](https://consul.io/docs/agent/checks.html) on `http://localhost:8085/health`.
 - **[registrator](https://github.com/gliderlabs/registrator)** to automatically expose weave-ip & services & container to docker/swarm on launch
 - **systemd** for starting apps inside containers
 - **[weave](https://github.com/zettio/weave#weave---the-docker-network)** for secure networking between containers [and DNS with consul backend](https://sttts.github.io/docker/weave/mesos/2015/01/22/weave.html)
 - **[shutit](https://ianmiell.github.io/shutit/)** for creating images (most basic linux there is)
 - **[EventStore](http://geteventstore.com)** for storing domain events
 - **[heka](https://hekad.readthedocs.org/en/latest/index.html)** for log shipping into InfluxDB and Greylog+ElasticSearch, with [docker](https://hekad.readthedocs.org/en/latest/config/inputs/docker_log.html) log input
 - **[influxdb](http://influxdb.com/)** for time-series data storage
 - **[grafana](http://grafana.org/)** for looking at InfluxDB data
 - **[bacula](http://blog.bacula.org/)** for backups

**Comment by ianmiell** [comment]
The short answer is "yes". It's a means of creating images to a spec when
Dockerfiles don't cut it, and those images should play nice with everything
else, as containers are contained :)

**Comment by ianmiell** [comment]
PS Demanding users are exactly what's needed for a project like this...

**Comment by ianmiell** [comment]
systemd request raised separately.
If you need it urgently, let me know - I may not get time to work on it for a while.

**Comment by haf** [comment]
Thanks, let me know though. =) Since all major distros are either using it or migrating to it (Debian), it seems wasteful to spend a lot of time with upstart scripts.

**Comment by ianmiell** [comment]
Agreed!
