### ISSUE TITLE
send() return value and exit_values argument

### ISSUE THREAD

**Issue by marcelloromani** [ianmiell/shutit#181]
```python
return_value = shutit.send('id {0}'.format(username), exit_values = ['0', '1'])
```
We have two scenarios:
a) `username` is known to the system* (e.g. `root`), hence `id` exit value is `0`
b) `username` is unknown to the system*, hence `id` exit value is `1`

What is the expected value if `return_value` in each scenario?

(If `exit_values` is omitted, an exception is raised in scenario b).

*system == container

**Comment by ianmiell** [comment]
The exit_values argument should be irrelevant - the return value is whatever was returned by the expect call for the command supplied.

Whether this is (still) a good idea or not is open to question.

**Comment by marcelloromani** [comment]
> The exit_values argument should be irrelevant

But it's there and appears in the documentation (and in `send()` code!). What is its purpose? (Or do you recommend not using it as it's to be removed?)

**Comment by marcelloromani** [comment]
> Whether this is (still) a good idea or not is open to question.

Sorry, I don't understand what you mean here.

**Comment by ianmiell** [comment]
send()

"        Returns the pexpect return value (ie which expected string in the
list
        matched)"

exit_values is to do with the exit code of the command sent:

        @param exit_values: Array of acceptable exit values as strings

so if an exit code of non-zero is ok (eg for grep) then an exception is not
thrown. It's nothing to do with the return value of the python send call
itself.

Does that make sense?

**Comment by marcelloromani** [comment]
Yes it does. Thank you.

[On a side note, I think there's an inconsistency in `send`'s doc about the `expect` parameter, but that might be the subject of another ticket or pull request... :) ]
