### ISSUE TITLE
Module documentation (esp. config keys)

### ISSUE THREAD

**Issue by marcelloromani** [ianmiell/shutit#183]
As far as I understand, currently the only way to discover which config keys a module uses and how it uses them is reading the source code.
I think eventually each module should provide a list of config keys and a synopsis for its use.

**Comment by ianmiell** [comment]
I started work on this a while ago - adding an arg to get_config to define its semantics. I'll try and remember to dig it up later.

**Comment by marcelloromani** [comment]
Having a list of config keys for a specific module id, along with their "hints" strings could be a good start IMHO.

**Comment by ianmiell** [comment]
....looks up python introspection tools...

**Comment by ianmiell** [comment]
Ideally we'd determine whether is_installed calls get_config and if so, call that module object's get_config.

The alternative is to call get_config on every single visible module, which doesn't seem ideal.

**Comment by marcelloromani** [comment]
Isn't get_config called before is_installed?

**Comment by ianmiell** [comment]
Not necessarily.

**Comment by marcelloromani** [comment]
(That reminded me of #180)

**Comment by ianmiell** [comment]
list_configs option available, or use -c
