### ISSUE TITLE
Location of build log file

### ISSUE THREAD

**Issue by marcelloromani** [ianmiell/shutit#184]
I can't find the build log after a build has successfully completed.
Inside the container I see a file in `/tmp` that has the same name mentioned in the all-red final shutit message, but it's an empty file.
Inside the host (i.e. where I run shutit build from) I can't find any log file either.

**Comment by marcelloromani** [comment]
The following are my findings so far (`util.py`, line 362 onwards).

The name of the log file is taken from the following config key:
```
[host]
log_file: /path/to/logfile
```
If that is not priovided, a default name is created:
```
/tmp/shutit_log + build_id
```
To have shutit write log messages to the file, the following config key must be used:
```
[build]
build_log: True
```

Note: if `build_log` is not a boolean value, an exception is thrown (`util.py`, line 297).

**Comment by marcelloromani** [comment]
Apparently, the default for `[build]build_log` is `no`, so the logfile is not produced unless the user adds the `build_log` line.

FWIW, I think it would be better to default this to yes, and produce a logfile for the user to review.

**Comment by ianmiell** [comment]
agreed.

**Comment by marcelloromani** [comment]
Considering #189, I think this can be closed.
