### ISSUE TITLE
The default expect stack seems to be broken

### ISSUE THREAD

**Issue by aidanhs** [ianmiell/shutit#186]
Any changes around here recently?

**Comment by aidanhs** [comment]
False alarm, a module had hardcoded `expect` in a call to shutit.file_exists to be shutit.cfg['expect_prompts']['root_prompt']

**Comment by aidanhs** [comment]
The value of root_prompt was 'SHUTIT_ROOT#4xS0SJVz>'. Is this correct? Didn't it use to be a generic root prompt?

**Comment by ianmiell** [comment]
A long time ago perhaps - it's not changed for a while. I think I made it work like all the other ones so that the mechanism was universal. Assuming this can be closed.
