### ISSUE TITLE
[proposal] eatmydata apt-get install to speed up builds

### ISSUE THREAD

**Issue by marcelloromani** [ianmiell/shutit#190]
Timed a few runs of a test module that just installs apache2 and maven.
A regular build took about 6'30".
Replacing apt-get install with eatmydata apt-get install inside ShutIt.install() brought the time down to about 2'20".

This could be activated via a `[build]` config item, e.g. `eatmydata: yes` (`no` by default, of course).

`eatmydata sudo docker build` could be effective as well (not tested yet)

This is the page that got me thinking:
http://unix.stackexchange.com/questions/7238/how-to-make-dpkg-faster

**Comment by ianmiell** [comment]
Interesting - the "eatmydata docker" approach won't work because the docker
call doesn't actually do the work!

It would have to be optional as eatmydata is unsafe. What if it were the
default for --debug?

**Comment by marcelloromani** [comment]
I think it should be separate from --debug.

Since to understand the tradeoffs one has to understand eatmydata in the fisrt place, I'd just add an --eatmydata option (or [build]eatmydata: yes config option).

In the future, if it proves safe enough `eatmydata apt-get install` could be the default, with an option like --sync-install or something to be used in case of problems.

**Comment by ianmiell** [comment]
I'm not sure a problem would necessarily be noticed... which makes it fine
for testing whether stuff "looks" ok, but not if you ever want to use the
artifact.

**Comment by ianmiell** [comment]
I'm unsure whether this is wise. People can put all sort of hacks to speed things up, this would open the door to them. And may create a lot of problems.

"In the future, if it proves safe enough eatmydata apt-get install could be the default, with an option like --sync-install or something to be used in case of problems."

This is definitely a "no" from me!

I wonder whether it's possible to have a module that sets this situation up for you?

**Comment by ianmiell** [comment]
http://superuser.com/questions/117227/a-command-before-every-bash-command

**Comment by ianmiell** [comment]
Write a module to add_to_bashrc() this line:

bind 'RETURN: "\e[1~eatmydata \e[4~\n"'

and install eatmydata and then you can include it in your builds on the command line "-s  moduleid buld yes" :)

Don't forget to submit it to me for the shutit library. It will make a great blog post :)

**Comment by ianmiell** [comment]
PS that's a really handy trick! Thanks for prompting me to find it!

**Comment by ianmiell** [comment]
I've drafted a module on the eatmydata branch. 

It fails on bash builtins though, eg: call exit when you get a prompt here:

shutit/library/eatmydata/bin $ ./build.sh 


SHUTIT_TMP#bB1StxE5>eatmydata exit
eatmydata error: unable to find 'exit' in PATH

altho you could cheat and change the command to append the same command at the end, eg:

SHUTIT_TMP#bB1StxE5>eatmydata exit || exit
eatmydata error: unable to find 'exit' in PATH
logout
SHUTIT_shutit.tk.eatmydata.eatmydata#BO8odvNA>


Example call when working:

shutit build -m ../eatmydata -s shutit.tk.eatmydata.eatmydata shutit.core.module.build yes

**Comment by marcelloromani** [comment]
Thanks. I'll have a look at your eatmydata branch.
In the meantime, I've drafted some code that adds "eatmydata" only to apt-get install commands (would need the same for yum install, which I haven't touched so far).
I'll post you a patch or raise a pull request ASAP so you can have a look.

**Comment by ianmiell** [comment]
Work continues in PR. Closing this off
