### ISSUE TITLE
apt-get update is called twice

### ISSUE THREAD

**Issue by marcelloromani** [ianmiell/shutit#191]
`apt-get update` is called once in `get_distro_info()`
https://github.com/ianmiell/shutit/blob/master/shutit_global.py#L1771

and then in setup.py, `setup` module:
https://github.com/ianmiell/shutit/blob/master/setup.py#L534
https://github.com/ianmiell/shutit/blob/master/setup.py#L547
https://github.com/ianmiell/shutit/blob/master/setup.py#L548

I think the call in `setup:build()` is triggered `do_update` being `yes` by default:
https://github.com/ianmiell/shutit/blob/master/util.py#L135
changin it to `no` fixed the issue.

**Comment by ianmiell** [comment]
I pondered this for a while and did something simpler - if we call apt-get update in the build then we switch off do_update. I'm not sure this is perfect but seems good enough and passes testing.

**Comment by marcelloromani** [comment]
Well, that's exacly what I did :-) I.e. changing `do_update` from `yes` to `no` in `util.py`

**Comment by marcelloromani** [comment]
It could be convenient to add some sort of "update packages" api to ShutIt, which would take care of remembering if we already called it and manage the commands for the specific target type (i.e. apt and yum).

Just a thought. I might draft something myself if I have time.
