### ISSUE TITLE
add entry_points to setup.py

### ISSUE THREAD

**Issue by FlorianLudwig** [ianmiell/shutit#196]
The setup.py should export cli scripts via the entry_points option.

for example:

    entry_points={
        'console_scripts': [
            'shutit = shutit.cli:main',
        ],
    },

**Comment by ianmiell** [comment]
Hi Florian, 

Thanks, I'll take a look. 

Do you have a reference for this? I'm not familiar with this pattern offhand (but will google).

Ian

**Comment by ianmiell** [comment]
http://www.scotttorborg.com/python-packaging/command-line-scripts.html

**Comment by ianmiell** [comment]
I'm not familiar with this packaging tool, but it seems that "setup" has a special meaning there that is not related to this project - am I correct? Here, setup.py is related to setting up the build environment for the automated build.

**Comment by FlorianLudwig** [comment]
@ianmiell oh,... `setup.py` is what the python module installation tools (like pip) execute to install a module.  Having a `setup.py` inside a python projects root suggests such usage.

Looking around the source it doesn't seem to be very "pythonic" :) Would patches be accepted to move towards a more pythonic packaing of shutit?

**Comment by ianmiell** [comment]
Absolutely!
Can we have a chat about how you came by this project? My mail is:
ian.miell@gmail.com
Ian

**Comment by marcelloromani** [comment]
Maybe the module just needs to be renamed to shutit_setup.py for clarity and consistency withthe  other files.
(The same applies to util.py, by the way.)

**Comment by ianmiell** [comment]
Moved files.

**Comment by FlorianLudwig** [comment]
I would like to suggest moving to a pythonic packaging anyway ;)

this would involve making shutit a python module:

	deleted:    shutit
	renamed:    shutit_global.py -> shutit/shutit_global.py
	renamed:    shutit_main.py -> shutit/shutit_main.py
	renamed:    shutit_module.py -> shutit/shutit_module.py
	renamed:    shutit_setup.py -> shutit/shutit_setup.py
	renamed:    shutit_srv.py -> shutit/shutit_srv.py
	renamed:    shutit_util.py -> shutit/shutit_util.py

Maybe even take a chance and rename them to `shutit/util.py` insteald of `shutit/shutit_util.py`.

and creating a "real" setup.py.

Example: https://github.com/FlorianLudwig/shutit/commit/01d3651274072d986663db77c226e239a2bfbf0f

Some refactoring for the imports etc. will be needed (And is not done in the example commit, so it won't work!)

Also moving data files around and using `pkg_resource` might be a good idea as well.

Is there interest in moving in this direction?

**Comment by ianmiell** [comment]
Yes - I think I've already moved the filenames away, so setup.py is now
"available"?
How's the evaluation going?
Ian
