### ISSUE TITLE
is_installed executed before get_config

### ISSUE THREAD

**Issue by aidanhs** [ianmiell/shutit#203]
A bit like #166.

Problem is here I think, but need to experiment - https://github.com/ianmiell/shutit/blob/07640a6164ac86438a7baa135a38be67cf7f0f78/shutit_main.py#L304-305

**Comment by aidanhs** [comment]
This is breaking my brain.

 - `is_installed` requires `get_config` to have run in order to have necessary config items available
 - but `get_config` can error if there are config items missing so it should only be run on modules which we expect to have configs set correctly (i.e. those to be built)
 - but `start`/`stop` should be run on any installed modules, so we need to check if *any* modules are installed
 - so we need to `get_config` on all modules
 - so we end up with errors!

Solution is one of
 - make `module.get_config` never fail, just return false. This also implies disabling interactive config prompting
 - make start/stop/test not run on all modules, only those listed in the current dependency tree.

I prefer option 2. If you have something that needs to be running, it should be a dep.

**Comment by aidanhs** [comment]
Option 2 doesn't work by itself, because we need to be able to check for conflicts over *all* modules. Which requires is_installed, which requires get config.

Better idea - is_installed should not depend on get_config.

**Comment by ianmiell** [comment]
No reports of this since March; tentatively closing.
