### ISSUE TITLE
Test don't run fully automatic

### ISSUE THREAD

**Issue by FlorianLudwig** [ianmiell/shutit#207]
The tests hang several times on

    Do you want to accept the config option defaults? (boolean - input "yes" or "no") (default: yes): 

Running the tests should not need any interaction.

**Comment by mromaniOB** [comment]
I believe there's a command-line option to bring down the "interactive"
level. The default is 3 IIRC, if run with 0 or 1 it should avoid user
interaction.

On 26 March 2015 at 13:34, Florian Ludwig <notifications@github.com> wrote:

> The tests hang several times on
>
> Do you want to accept the config option defaults? (boolean - input "yes"
> or "no") (default: yes):
>
> Running the tests should not need any interaction.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ianmiell/shutit/issues/207>.
>



-- 
  <http://www.openbet.com> Marcello Romani  Developer   T: +44 208 742 1600




   E: marcello.romani@openbet.com  W: www.openbet.com    OpenBet Ltd
Chiswick Park Building 9
566 Chiswick High Rd
London
W4 5XT   <http://twitter.com/OpenBet_Ltd>
<http://www.linkedin.com/company/165331/>
<http://www.facebook.com/OpenBet>  *EGR
B2B Awards*
Five times winner of Sportsbetting Supplier of the Year 2010 - 2014
Winner of In-Play Betting Software of the Year 2014  This message is
confidential and intended only for the addressee. If you have received this
message in error, please immediately notify the postmaster@openbet.com and
delete it from your system as well as any copies. The content of e-mails as
well as traffic data may be monitored by OpenBet for employment and
security purposes. To protect the environment please do not print this
e-mail unless necessary. OpenBet Ltd. Registered Office: Chiswick Park
Building 9, 566 Chiswick High Road, London, W4 5XT, United Kingdom. A
company registered in England and Wales. Registered no. 3134634. VAT no.
GB927523612  [image: save paper]

**Comment by ianmiell** [comment]
suspect this is not handled correctly atm. Willfix.

**Comment by ianmiell** [comment]
Have corrected this, and also taken out library tests. Libraries are to be deprecated from this repo.
