### ISSUE TITLE
Error during pip installation

### ISSUE THREAD

**Issue by alx741** [ianmiell/shutit#253]
I'm not sure this is a **shutit** problem or something about my system.

Running `sudo pip install shutit` I get:

    Collecting shutit
      Using cached shutit-0.9.163.tar.gz
        Complete output from command python setup.py egg_info:
        Traceback (most recent call last):
          File "<string>", line 1, in <module>
          File "/tmp/pip-build-sewjyeur/shutit/setup.py", line 10, in <module>
            with open(path.join(here, 'DESCRIPTION.rst'), encoding='utf-8') as f:
          File "/usr/lib/python3.5/codecs.py", line 895, in open
            file = builtins.open(filename, mode, buffering)
         FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-build-sewjyeur/shutit     /DESCRIPTION.rst'

         ----------------------------------------
     Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-sewjyeur/shutit/

**Comment by ianmiell** [comment]
Hi,
I just tested with a vanilla 16.04 xenial ubuntu VM and it was ok. Which OS are you using?
Ian

**Comment by alx741** [comment]
oh! sorry I omitted such important information!
I'm using Archlinux

`$ python --version`

gives

    Python 3.5.1

and 

`$ pip --version`

gives

    pip 8.1.2 from /usr/lib/python3.5/site-packages (python 3.5)

**Comment by ianmiell** [comment]
Ooh, ok is there a vagrant vm that's close?

**Comment by alx741** [comment]
This one over here reproduces the problem perfectly:
https://github.com/Dreamscapes/atlas-archlinux

Installing *python* and *pip* with (In the Archlinux vm):

    $ sudo pacman -Syy
    $ sudo pacman -S python python-pip

Then installing *shutit* with pip:

    $ pip install shutit

Gives the same error

**Comment by ianmiell** [comment]
As a workaround, this works:

```
vagrant@archlinux:~$ git clone https://github.com/ianmiell/shutit
Cloning into 'shutit'...
remote: Counting objects: 26534, done.
remote: Compressing objects: 100% (44/44), done.
remote: Total 26534 (delta 28), reused 0 (delta 0), pack-reused 26490
Receiving objects: 100% (26534/26534), 12.36 MiB | 2.63 MiB/s, done.
Resolving deltas: 100% (15460/15460), done.
Checking connectivity... done.
vagrant@archlinux:~$ cd shutit/
vagrant@archlinux:~/shutit$ sudo pip install .
Processing /home/vagrant/shutit
Collecting pexpect>=4.0 (from shutit==0.9.162)
  Downloading pexpect-4.1.0-py2.py3-none-any.whl (54kB)
    100% |████████████████████████████████| 61kB 2.0MB/s 
Collecting jinja2>=0.1 (from shutit==0.9.162)
  Downloading Jinja2-2.8-py2.py3-none-any.whl (263kB)
    100% |████████████████████████████████| 266kB 2.7MB/s 
Collecting pynsca>=1.5 (from shutit==0.9.162)
  Downloading pynsca-1.5.tar.gz
Collecting texttable>=0.1 (from shutit==0.9.162)
  Downloading texttable-0.8.4.tar.gz
Collecting ptyprocess>=0.5 (from pexpect>=4.0->shutit==0.9.162)
  Downloading ptyprocess-0.5.1-py2.py3-none-any.whl
Collecting MarkupSafe (from jinja2>=0.1->shutit==0.9.162)
  Downloading MarkupSafe-0.23.tar.gz
Installing collected packages: ptyprocess, pexpect, MarkupSafe, jinja2, pynsca, texttable, shutit
  Running setup.py install for MarkupSafe ... done
  Running setup.py install for pynsca ... done
  Running setup.py install for texttable ... done
  Running setup.py install for shutit ... done
Successfully installed MarkupSafe-0.23 jinja2-2.8 pexpect-4.1.0 ptyprocess-0.5.1 pynsca-1.5 shutit-0.9.162 texttable-0.8.4
vagrant@archlinux:~/shutit$ 
```

stumped on the other one, will keep looking.

**Comment by ianmiell** [comment]
Fixed (v 0.9.167).

BTW, what got you interested in ShutIt? I can add archlinux support if you want?

Keep in touch!

**Comment by alx741** [comment]
Thank you very much, really appreciate it.

I got this problem when trying your docker-101-tutorial, I find it really interesting!

**Comment by ianmiell** [comment]
Great!
Contributions welcome.

On Thu, May 26, 2016 at 4:08 PM, Daniel Campoverde <notifications@github.com
> wrote:

> Thank you very much, really appreciate it.
>
> I got this problem when trying your docker-101-tutorial, I find it really
> interesting!
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> <https://github.com/ianmiell/shutit/issues/253#issuecomment-221899255>
>



-- 
My book on Docker in Practice: Get 39% off with the code 39miell
<http://manning.com/miell/?a_aid=zwischenzugs&a_bid=e0d48f62>
