### ISSUE TITLE
Ctrl + ] is extremely difficult to type on a french Mac keyboard ('Azerty')

### ISSUE THREAD

**Issue by hajdbo** [ianmiell/shutit#256]
]  is  Alt + Shift + )
Ctrl + ] should be Ctrl + Alt + Shift + ), but doesn't work by default on iTerm2.
I had to configure iTerm2 profile to set a new shortcut: 
<img width="916" alt="screen shot 2016-06-04 at 22 49 41" src="https://cloud.githubusercontent.com/assets/1834306/15802053/b6234680-2aa7-11e6-942a-78f67d0227a7.png">

**Comment by ianmiell** [comment]
Oh! I used that because it's the escape code in telnet.
Thanks for that, I'll have a think about what would be better.
Any suggestions? What do you do for telnet?

On Sat, Jun 4, 2016 at 9:58 PM, Boris Hajduk <notifications@github.com>
wrote:

> ] is Alt + Shift + )
> Ctrl + ] should be Ctrl + Alt + Shift + ), but doesn't work by default on
> iTerm2.
> I had to configure iTerm2 profile to set a new shortcut:
> [image: screen shot 2016-06-04 at 22 49 41]
> <https://cloud.githubusercontent.com/assets/1834306/15802053/b6234680-2aa7-11e6-942a-78f67d0227a7.png>
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/ianmiell/shutit/issues/256>, or mute the thread
> <https://github.com/notifications/unsubscribe/AGrczZrFYpgn8B3Q6VU2tbUXN3egeUg1ks5qIebrgaJpZM4IuN6o>
> .
>



-- 
My book on Docker in Practice: Get 39% off with the code 39miell
<http://manning.com/miell/?a_aid=zwischenzugs&a_bid=e0d48f62>

**Comment by hajdbo** [comment]
http://superuser.com/a/427/138218

On international keyboards the ] character is often not a single key, and needs to be replaced with some other key. The correct key is typically the key to the right of P or the next key after that.

Here's a list based on comments below:
  
 - Finnish, Swedish, Norwegian, Danish: <kbd>ctrl</kbd> + <kbd>å</kbd>
 - French: <kbd>ctrl</kbd> + <kbd>6</kbd>
 - German: <kbd>ctrl</kbd> + <kbd>ü</kbd>
 - Swiss: <kbd>ctrl</kbd> + <kbd>¨</kbd>
 - Hungarian: <kbd>ctrl</kbd> + <kbd>5</kbd>
 - Portuguese: <kbd>ctrl</kbd> + <kbd>´</kbd>
 - Dutch, Belgian: <kbd>ctrl</kbd> + <kbd>$</kbd>
 - Canadian French: <kbd>ctrl</kbd> + <kbd>ç</kbd>

**Comment by ianmiell** [comment]
Thanks Boris, have added a link to that in the comments in the code.

On Mon, Jun 6, 2016 at 3:23 PM, Boris Hajduk <notifications@github.com>
wrote:

> Closed #256 <https://github.com/ianmiell/shutit/issues/256>.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/ianmiell/shutit/issues/256#event-682921133>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AGrczSxi-E9-OL0dKmIwng5h8-pYp5DVks5qJC19gaJpZM4IuN6o>
> .
>



-- 
My book on Docker in Practice: Get 39% off with the code 39miell
<http://manning.com/miell/?a_aid=zwischenzugs&a_bid=e0d48f62>
