### ISSUE TITLE
ShutIt Web UI improvements

### ISSUE THREAD

**Issue by aidanhs** [ianmiell/shutit#29]
Umbrella ticket for my thoughts. This comment will be updated as things change.

Vital:
 - [x] Actually print the container id of the container we build.
 - [x] Allow a user to start a new build without restarting the server.
 - [x] Give user an interface for manipulating config in the browser.
 - [ ] Long polling and/or websockets to throttle requests
 - [ ] Allow multiple simultaneous builds (this is impossible while things are still using the old util.* functions...can we detect and degrade?).
 - [ ] More robust container cleanup.

Nice to have:
 - [x] Provide a link to download the container as a gzip (only useful where shutit is being used on a 'build box', do we care about this kind of environment?)
 - [ ] Show number of connected users on server.
 - [ ] Warning when disconnected from server.
 - [ ] Request queue to make sure the server isn't being spammed if it's slow to respond.
 - [ ] Integrate with docker terminal.

Needs thought:

**Comment by ianmiell** [comment]
Closing this pending a revival of the UI.
