### ISSUE TITLE
move /tmp dir to home/.shutit/tmp

### ISSUE THREAD

**Issue by ianmiell** [ianmiell/shutit#298]
some users can't write to /tmp

**Comment by jamiesonbecker** [comment]
Well, insecure tmp file creation is a primary attack vector for me; I wasn't able to quickly track down where /tmp is hard-coded, but in general just avoid /tmp or _any_ other directory specifically -- let Python create your file for you with mkstemp or mkdtemp:

https://docs.python.org/2/library/tempfile.html#tempfile.mkstemp

You can specify a specific directory if needed on a different filesystem, but if someone can't write to /tmp, then it's a broken system and probably out of compliance with the LSB/FHS.)

**Comment by ianmiell** [comment]
I think I resolved this - will re-check.

Thanks for the tip, I'll follow that up. I have run into obscure issues around these things with Cygwin et al.

**Comment by ianmiell** [comment]
There are systems we have at work (highly regulated/secure env) where one can't write to tmp. PITA.

**Comment by jamiesonbecker** [comment]
Good point with regards to cygwin!
