### ISSUE TITLE
ShutIt is slightly painful to get started with

### ISSUE THREAD

**Issue by aidanhs** [ianmiell/shutit#30]
Docker is approximately zero-dep. Compare with shutit:
```
sudo apt-get install python-virtualenv
git clone https://github.com/ianmiell/shutit.git
cd shutit
virtualenv .
. bin/activate
pip install bottle pexpect
vim configs/defaults.cnf
```

Variations exist (no virtualenv and apt-get the deps instead, create a new config rather than editing the existing one), but the general idea remains the same - there's too much friction.

**Comment by hlgr360** [comment]
I was intrigued to get a Taiga image build but after two days I have to admit that this is way too complicated. I have not been able to replicate the Taiga.io build .. there seems to be some baseline config and environment variables missing 

Here is what I did

This docker file https://raw.githubusercontent.com/ianmiell/shutit/master/library/taigaio/dockerfile/Dockerfile
pointed to from
https://github.com/taigaio/taiga-scripts/issues/3
does not seem to work - at least not with the phusion image (ubuntu image tailored for docker)

This is as far as I got

'''
# Install shutit
# See https://github.com/ianmiell/shutit/blob/master/INSTALL.md
RUN apt-get install -y -qq curl git python-pip
WORKDIR /opt
RUN git clone https://github.com/ianmiell/shutit.git
WORKDIR /opt/shutit
RUN pip install -r requirements.txt

# Build taiga.io
# See https://github.com/taigaio/taiga-scripts/issues/3
# and https://zwischenzugs.wordpress.com/2014/10/07/using-shutit-to-build-your-own-taiga-server/
WORKDIR /opt/shutit/library/taigaio/bin
'''

Trying to run the build interactively at this point complains about wrong permissions and missing env variables

So I manually did the following in my shell 
'''
export PATH=$PATH:/opt/shutit
export SHUTIT=/opt/shutit/shutit
chmod 0600 configs/build.cnf
'''

But I am unable to get beyond the following point

'''
root@5361044cc010:/opt/shutit/library/taigaio/bin# /opt/shutit/shutit build --shutit_module_path /opt/shutit/library --delivery bash --debug --interactive 0
Manhole[1423390321.8383]: Patched <built-in function fork> and <built-in function forkpty>.
LOG: 2015-02-08 10:12:01 Loading source for: /opt/shutit/setup.py
LOG: 2015-02-08 10:12:01 ShutIt module paths now: 
LOG: 2015-02-08 10:12:01 ['/opt/shutit/library', '.']
Manhole[1423390321.8546]: Manhole UDS path: /tmp/manhole-117
Manhole[1423390321.8672]: Waiting for new connection (in pid:117) ...
LOG: 2015-02-08 10:12:02 Loading source for: /opt/shutit/library/docker/docker.py
LOG: 2015-02-08 10:12:02 Loading source for: /opt/shutit/library/weave/weave.py

(lots of libs)

LOG: 2015-02-08 10:12:03 Loading source for: /opt/shutit/library/hostx/hostx.py
LOG: 2015-02-08 10:12:03 Loading source for: /opt/shutit/library/spidermonkey/spidermonkey.py
LOG: 2015-02-08 10:12:03 PHASE: base setup
ERROR!

Config item: shutit.core.module.remove:
in module:
[shutit.tk.setup]
must be set!

Often this is a deliberate requirement to place in your ~/.shutit/config file, or you can pass in with:

-s shutit.tk.setup shutit.core.module.remove yourvalue

to the build command
'''

Even though I specified non-interactive in the command line. Running the '''bin/build.sh''' prompts through a myriad of configuration items I have no clue about .. what is frustrating is that most of the settings have defaults, yet I am unable to accept them without manually being prompted

'''
root@5361044cc010:/opt/shutit/library/taigaio# /opt/shutit/shutit build --shutit_module_path /opt/shutit/library --delivery bash --debug

(lots of libs)

LOG: 2015-02-08 09:47:46 Loading source for: /opt/shutit/library/spidermonkey/spidermonkey.py
LOG: 2015-02-08 09:47:46 PHASE: base setup


Please input a value for shutit.tk.setup.shutit.core.module.remove (default: False) (boolean - input "yes" or "no"): 



Please input a value for shutit.tk.setup.shutit.core.module.remove (default: False) (boolean - input "yes" or "no"): 



Please input a value for shutit.tk.setup.shutit.core.module.remove (default: False) (boolean - input "yes" or "no"): 



Please input a value for shutit.tk.setup.shutit.core.module.remove (default: False) (boolean - input "yes" or "no"): 



Please input a value for shutit.tk.setup.shutit.core.module.remove (default: False) (boolean - input "yes" or "no"): 



Please input a value for shutit.tk.setup.shutit.core.module.remove (default: False) (boolean - input "yes" or "no"): 



Please input a value for shutit.tk.setup.shutit.core.module.remove (default: False) (boolean - input "yes" or "no"): 
no


Please input a value for shutit.tk.setup.shutit.core.module.tag (default: False) (boolean - input "yes" or "no"): 
no


Please input a value for shutit.tk.setup.shutit.core.module.allowed_images (default: ['.*']): 
no


Please input a value for shutit.tk.setup.shutit.core.module.build_ifneeded (default: False) (boolean - input "yes" or "no"): 
no


Please input a value for shutit.tk.supervisor.supervisor.shutit.core.module.remove (default: False) (boolean - input "yes" or "no"): 
no


Please input a value for shutit.tk.supervisor.supervisor.shutit.core.module.tag (default: False) (boolean - input "yes" or "no"): 
no


Please input a value for shutit.tk.supervisor.supervisor.shutit.core.module.allowed_images (default: ['.*']): 
no


Please input a value for shutit.tk.supervisor.supervisor.shutit.core.module.allowed_images (default: [u'ubuntu:14.04']): 
u 
'''

At which point I am giving up. There is nothing in the documentation indicating that some default configuration needs to be created nor how it can be generated. I found some pointer to a default config in uti.py .. but even after extracting and copying that to ~/.shutit/config I am still prompted to select a million options. 

There appears to be a basic install/config step missing which is not apparent.

So I can only agree with the initial issue raised - great idea but unless it is dead simple to get some example like taiga.io to build 'out of the box' it is 'software written by PhDs for PhDs' and won't live up to its potential. :)

**Comment by ianmiell** [comment]
Hi!

Thanks very much for getting in touch!

Unfortunately you may have seen shutit in a state while I was hacking on
it, as I wasn't aware people were using it in anger. I'm out and about
today so I'll get back to you when I have a moment. Just looking at this
briefly, if you git pull again it should just ask you to accept the
defaults at the start and then it should be fine, but yes making it easier
to get started with is something I'd like to keep talking to you about.

I'll be back in touch :)

Ian

**Comment by hlgr360** [comment]
No problem .. 

>  I wasn't aware people were using it in anger

I would not characterize it that way .. just that something basic was missing .. :)
-----
launchd.io | launchd.de
email: holger@launchd.de
blog: http://hlgr360.wordpress.com

Sitz der Gesellschaft: Esslingen | Rechtsform: GbR
Geschäftsführer: Holger Reinhardt & Jonas Dagefoerde
USt-IdNr.: DE288302537

**Comment by hlgr360** [comment]
I should clarify my goal - I would like to be able to build the taiga (or any other container) within a vagrant box (in my case boot2docker). you can find my setup here: https://github.com/hlgr360/docker-templates/tree/master/project

**Comment by ianmiell** [comment]
*Headline: *

The latest build was broken. I've fixed it, thanks to your feedback :)

As for the original aim, I think your Vagrantfile was wrong. A corrected
one is attached, which appeared to work for me. Note I changed to port 8010
to avoid a clash on my machine, so the output is slightly different.

Comma required here:
https://github.com/hlgr360/docker-templates/blob/master/project/Vagrantfile#L46


and see point 3) below (the start command was wrong)b.

==> boot2docker: a49554239e0e: Download complete
==> boot2docker: a49554239e0e: Download complete
==> boot2docker: Status: Downloaded newer image for imiell/taigaio:latest
==> boot2docker: Starting Docker containers...
==> boot2docker: -- Container: taigaio
imiell@rothko:/space/vagrant/hlgr360$ vagrant ssh
/opt/vagrant/bin/../embedded/gems/gems/vagrant-1.7.2/lib/vagrant/pre-rubygems.rb:31:
warning: Insecure world writable dir /space in PATH, mode 040777
/opt/vagrant/embedded/gems/gems/bundler-1.7.11/lib/bundler/runtime.rb:222:
warning: Insecure world writable dir /space in PATH, mode 040777
                        ##        .
                  ## ## ##       ==
               ## ## ## ##      ===
           /""""""""""""""""\___/ ===
      ~~~ {~~ ~~~~ ~~~ ~~~~ ~~ ~ /  ===- ~~~
           \______ o          __/
             \    \        __/
              \____\______/
 _                 _   ____     _            _
| |__   ___   ___ | |_|___ \ __| | ___   ___| | _____ _ __
| '_ \ / _ \ / _ \| __| __) / _` |/ _ \ / __| |/ / _ \ '__|
| |_) | (_) | (_) | |_ / __/ (_| | (_) | (__|   <  __/ |
|_.__/ \___/ \___/ \__|_____\__,_|\___/ \___|_|\_\___|_|
Boot2Docker version 1.4.1, build yungsang/boot2docker : 7683f7c - Sat Dec
20 05:05:14 UTC 2014
Docker version 1.4.1, build 5bc2ff8
docker@boot2docker:~$ docker ps
CONTAINER ID        IMAGE                   COMMAND                CREATED
            STATUS              PORTS                    NAMES
e93bf8c9ea18        imiell/taigaio:latest   "bash -c '/root/star   38
seconds ago      Up 37 seconds       0.0.0.0:8010->8000/tcp   taigaio



*1) ShutIt Module*

There was a bug in the script (an API change requiring an update to the
taigaio.py script). This has been fixed and pushed.

*2) Dockerfile not working.*

The Dockerfile hangs for me mid-build. This looks like the mysterious
"docker build can't take much output before it dies" (it stops around
trying to install python) problem I've seen before and haven't got to the
bottom of. I suspect a bug in Docker somewhere, but have no evidence.

I changed it to output less (no debug) and this worked for me:

$ docker build --no-cache
https://raw.githubusercontent.com/ianmiell/shutit/master/library/taigaio/dockerfile/Dockerfile


*3) Vagrant*

"I should clarify my goal - I would like to be able to build the taiga (or
any other container) within a vagrant box (in my case boot2docker). you can
find my setup here:
https://github.com/hlgr360/docker-templates/tree/master/project"

I got this working by altering line 46 to add a comma:

https://github.com/hlgr360/docker-templates/blob/master/project/Vagrantfile#L46

and started up the VM, ssh'd in and waited for vagrant to attempt to
install the image. This was the error:

==> boot2docker: Status: Downloaded newer image for imiell/taigaio:latest
==> boot2docker: Starting Docker containers...
==> boot2docker: -- Container: taigaio
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!


          rm -f
/var/lib/vagrant/cids/7f70b9b34b08143080701e24367d98abaa9e94b9
          docker run
--cidfile=/var/lib/vagrant/cids/7f70b9b34b08143080701e24367d98abaa9e94b9 -d
--name taigaio -it -p 8010:8000 imiell/taigaio /root/start_postgres.sh &&
/root/start_taiga.sh && echo READY! && sleep infinity


Stdout from the command:

245a1c0dcf6c52f8c25e9171452c981503b42be863fb797588159678c2d308ce


Stderr from the command:

time="2015-02-08T19:30:58Z" level="fatal" msg="Error response from daemon:
Cannot start container
245a1c0dcf6c52f8c25e9171452c981503b42be863fb797588159678c2d308ce: exec
format error"


I then ran:

docker@boot2docker:~$ docker run -i -t -p 127.0.0.1:8000:8000 -p
127.0.0.1:8001:8001 imiell/taigaio bash -c '/root/start_postgres.sh && /roo
t/start_taiga.sh && echo READY! && sleep infinity'
Setting shmmax for postgres
sysctl: setting key "kernel.shmmax": Read-only file system
 * Starting PostgreSQL 9.3 database server
                                                          [ OK ]
READY!


as per the blog entry:

https://zwischenzugs.wordpress.com/2014/10/07/using-shutit-to-build-your-own-taiga-server/

and it worked.


Let me know if this doesn't make sense at all!

BTW, "in anger" means "not for practise or testing" in colloquial English:

https://www.englishforums.com/English/SourceExpressionAnger/jkkzb/post.htm

and (usually) has nothing to do with anger!

Ian

On Sun, Feb 8, 2015 at 3:51 PM, Holger Reinhardt <notifications@github.com>
wrote:

> I should clarify my goal - I would like to be able to build the taiga (or
> any other container) within a vagrant box (in my case boot2docker). you can
> find my setup here:
> https://github.com/hlgr360/docker-templates/tree/master/project
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ianmiell/shutit/issues/30#issuecomment-73416569>.
>

**Comment by hlgr360** [comment]
Awesome .. thanks. I will check it out later tonight. Question for my better understanding - is there a reason to bundle multiple processes in a single docker container rather than stick to the convention of a single process within each individual container?
 
-----
launchd.io | launchd.de
email: holger@launchd.de
blog: http://hlgr360.wordpress.com

Sitz der Gesellschaft: Esslingen | Rechtsform: GbR
Geschäftsführer: Holger Reinhardt & Jonas Dagefoerde
USt-IdNr.: DE288302537

**Comment by ianmiell** [comment]
A very good question!

Opinion is divided on the subject. Generally people argue for multiple
containers, one per process. And I suppose that is the ideal.

As a working engineer though, sometimes I just want to get going quickly
and manage one unit (if I think of taigaio as a unit, and not discrete
services). In my last company, monolithic containers saved us a lot of time
and money.

In this case, setting up taigaoio was such a pain that I thought putting it
in one container to play with it made sense.

Keep in touch,

Ian

**Comment by mromaniOB** [comment]
Can `pip`'s option `--user`, be used to avoid `virtualenv`?

```bash
git clone https://github.com/ianmiell/shutit.git
cd shutit
pip install --user -r requirements.txt
```

**Comment by ianmiell** [comment]
Above implemented. Closing this off for now.
