### ISSUE TITLE
Cannot keep connection when logged in to remote server

### ISSUE THREAD

**Issue by jimmytuc** [ianmiell/shutit#316]
I'm always faced with this problem when trying to log in via `bash` script
<img width="945" alt="screenshot at may 17 18-24-23" src="https://user-images.githubusercontent.com/3124405/40174631-e9594b92-59ff-11e8-8aea-4db8de7bfc5d.png">

Have anyone solved this?

**Comment by ianmiell** [comment]
Is bash installed on the host (so I can run it up if it's seen?) - it's
kind of an assumption that bash is available.

Also, what's the wider use case? I'm always curious to know whether I can
help achieve your goal.

**Comment by jimmytuc** [comment]
Thanks for your responses @Ianmiell
Yes, I'm using iTerm2 for mac

My use case is auto the deployment to multiple staging hosts whenever code committed.

Thanks for any advices.

**Comment by ianmiell** [comment]
Can you re-run with --debug and send me the output? Thanks.

**Comment by jimmytuc** [comment]
You're right, @ianmiell 

I've changed the default shell to `bash` on the remote host.
It's working now.

Many thanks.

**Comment by jimmytuc** [comment]
I will upgrade your latest update on it after I've done some automate tasks on shutit.

Thanks for your help.

**Comment by ianmiell** [comment]
James, great news, thanks.
If you can give me feedback on any docs and/or ask me for help when needed
that would be great.
Ian

**Comment by jimmytuc** [comment]
Sure, Ian
