### ISSUE TITLE
Can't determine Linux Distro information - Amazon Linux 2 AMI

### ISSUE THREAD

**Issue by byKirby** [ianmiell/shutit#324]
Tried running this on a minimal install AWS EC2 instance on an Amazon Linux AMI, but ran into an issue of `"Could not determine Linux Distro information"` error. Looked through passed issues and looks like you had addressed this, but maybe I'm missing something? I installed shutit via pip, cloned the project and then ran `./copy-server.sh`

Also gave the shutit CLI tool a go, but run into the same issue after selecting to build a Docker image.

I'd be happy to supply any more information you might need.

![image](https://user-images.githubusercontent.com/7763844/43978704-caf6f55a-9cad-11e8-9dfb-e785659aa3a1.png)

**Comment by ianmiell** [comment]
Sorry about the delay getting back to you. Can you get the entire debug
output of the run into a file/entry for me to examine?
Thanks,
Ian
