### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by aidanhs** [ianmiell/shutit#33]
We need it. Example:

A user was confused by what send_and_expect returned.
I explained like so
```
shutit.send_and_expect('echo aaa', expect=["aaa", "bbb","ccc"]) == 0
shutit.send_and_expect('echo bbb', expect=["aaa", "bbb","ccc"]) == 1
shutit.send_and_expect('echo ccc', expect=["aaa", "bbb","ccc"], exit_values=['0','1']) == 2
shutit.send_and_expect('echo aaa', expect=["aaa", "bbb","ccc"], exit_values=['2','3']) -> explodes
```

**Comment by ianmiell** [comment]
Reviving this as per Marcello's post.
Have added a lot of unchecked auto-gen'd docs from epydoc. See docs/dev/html/README.md

**Comment by ianmiell** [comment]
Documentation is there now (thought never "complete")
