### ISSUE TITLE
privileged should not be required.

### ISSUE THREAD

**Issue by ianmiell** [ianmiell/shutit#91]
Require privileged only when needed.

Requires us to restart shutit ui fully when running, and also to determine whether priv needed. Also applies to main code.

**Comment by ianmiell** [comment]
Done.

**Comment by aidanhs** [comment]
Done in what way?

**Comment by ianmiell** [comment]
Privileged is now not switched on by default (it was for a good while).

**Comment by aidanhs** [comment]
I feel we need a breaking change changelog - that will surely break things like sshd.

**Comment by aidanhs** [comment]
Er, I mean sshfs

**Comment by ianmiell** [comment]
You can still set it if you need it? --privileged flag

Happy to have a breaking change changelog though - never felt it was needed
before.

**Comment by ianmiell** [comment]
Another thought occurs - this was a pretty blunt instrument, so there should probably be functionality to add capability requirements per-module.
